#!/bin/bash
# IntelliHire Backend Setup & Run Guide

echo "================== IntelliHire Backend Setup =================="
echo ""
echo "Step 1: Install Python Dependencies"
echo "-----------------------------------"
echo "cd backend"
echo "pip install -r requirements.txt"
echo ""

echo "Step 2: Start MongoDB"
echo "-------------------"
echo "Option A - Local MongoDB:"
echo "  mongod"
echo ""
echo "Option B - Docker:"
echo "  docker run -d -p 27017:27017 mongo:latest"
echo ""

echo "Step 3: Run Backend Server"
echo "------------------------"
echo "python main.py"
echo ""
echo "Server will be available at:"
echo "  - Base URL: http://localhost:8000"
echo "  - API Docs: http://localhost:8000/docs"
echo "  - Health: http://localhost:8000/health"
echo ""

echo "Step 4: Run Tests (Optional)"
echo "--------------------------"
echo "pytest backend/tests/ -v"
echo "Expected: 53 tests passed ✅"
echo ""

echo "Step 5: Connect React Frontend"
echo "-----------------------------"
echo "Frontend (in separate terminal/process):"
echo "  cd frontend"
echo "  npm run dev"
echo ""
echo "Frontend will connect to: http://localhost:8000/api/*"
echo ""

echo "================== API Endpoints =================="
echo ""
echo "CANDIDATES:"
echo "  POST   /api/candidates/upload-resume"
echo "  GET    /api/candidates/list"
echo "  GET    /api/candidates/{id}"
echo "  GET    /api/candidates/search/by-skill?skill=python"
echo "  DELETE /api/candidates/{id}"
echo ""
echo "JOBS:"
echo "  POST   /api/jobs/create"
echo "  GET    /api/jobs/list"
echo "  GET    /api/jobs/{id}"
echo "  PUT    /api/jobs/{id}"
echo "  DELETE /api/jobs/{id}"
echo ""
echo "MATCHING (LCS Algorithm):"
echo "  POST /api/matching/calculate-score?candidate_id=X&job_id=Y"
echo "  GET  /api/matching/top-candidates/{job_id}"
echo "  GET  /api/matching/job/{job_id}"
echo ""
echo "SCHEDULER (Knapsack + Activity Selection):"
echo "  POST /api/scheduler/rank-candidates/{job_id}"
echo "  POST /api/scheduler/schedule-interviews/{job_id}"
echo "  GET  /api/scheduler/get-schedule/{job_id}"
echo "  GET  /api/scheduler/get-ranking/{job_id}"
echo ""

echo "================== Environment Info =================="
echo "Python: $(python --version)"
echo "MongoDB: Required (local or Docker)"
echo "FastAPI: Auto-reload enabled in dev mode"
echo "CORS: Enabled for localhost:3000, localhost:5173"
echo ""
echo "✅ Backend is ready!"
